select
  название_функции(СТОЛБЕЦ_ДЛЯ_ВЫЧИСЛЕНИЙ) 
  over (partition by СТОЛБЕЦ_ДЛЯ_ГРУППИРОВКИ order by СТОЛБЕЦ_ДЛЯ_СОРТИРОВКИ)
from
  employees
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  FIRST_VALUE(FIRST_NAME) OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC) as HIGHEST_PAID_EMPLOYEE
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  FIRST_VALUE(FIRST_NAME ||' '|| LAST_NAME) OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC) as HIGHEST_PAID_EMPLOYEE
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  FIRST_VALUE(FIRST_NAME ||' '|| LAST_NAME) OVER (PARTITION BY JOB_ID ORDER BY SALARY ASC) as LOWEST_PAID_EMPLOYEE
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  FIRST_VALUE(FIRST_NAME ||' '|| LAST_NAME) OVER (PARTITION BY JOB_ID ORDER BY SALARY ASC) as LOWEST_PAID_EMPLOYEE,
  LAST_VALUE(FIRST_NAME ||' '|| LAST_NAME) OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC) as LOWEST_PAID_EMPLOYEE_2
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  FIRST_VALUE(FIRST_NAME ||' '|| LAST_NAME) OVER (PARTITION BY JOB_ID ORDER BY SALARY ASC) as LOWEST_PAID_EMPLOYEE,
  LAST_VALUE(FIRST_NAME ||' '|| LAST_NAME) OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as LOWEST_PAID_EMPLOYEE_2
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  FIRST_VALUE(FIRST_NAME ||' '|| LAST_NAME) OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC) as HIGHEST_PAID_EMPLOYEE
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  NTH_VALUE(FIRST_NAME ||' '|| LAST_NAME, 1) OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC) as HIGHEST_PAID_EMPLOYEE
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  NTH_VALUE(FIRST_NAME ||' '|| LAST_NAME, 2) OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC) as HIGHEST_PAID_EMPLOYEE
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  NTH_VALUE(FIRST_NAME ||' '|| LAST_NAME, 2) OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as HIGHEST_PAID_EMPLOYEE
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  JOB_ID,
  NTH_VALUE(SALARY, 3) OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as HIGHEST_PAID_EMPLOYEE
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  distinct JOB_ID,
  NTH_VALUE(SALARY, 3) OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as HIGHEST_PAID_EMPLOYEE
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  LAG(FIRST_NAME, 1) OVER (PARTITION BY JOB_ID ORDER BY SALARY) as MIN_SALARY
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  LAG(FIRST_NAME, 2) OVER (PARTITION BY JOB_ID ORDER BY SALARY) as MIN_SALARY
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  LAG(FIRST_NAME, 2, '-') OVER (PARTITION BY JOB_ID ORDER BY SALARY) as MIN_SALARY
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  LEAD(FIRST_NAME, 2, '-') OVER (PARTITION BY JOB_ID ORDER BY SALARY) as MAX_SALARY
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  LEAD(FIRST_NAME, 1, '-') OVER (PARTITION BY JOB_ID ORDER BY SALARY) as MAX_SALARY
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG', 'PU_CLERK')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  RATIO_TO_REPORT(SALARY) OVER (PARTITION BY JOB_ID) as RATIO_SALARY
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  RATIO_TO_REPORT(SALARY) OVER (PARTITION BY JOB_ID ORDER BY SALARY) as RATIO_SALARY
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY,
  RATIO_TO_REPORT(SALARY) OVER () as RATIO_SALARY
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG')
;


select
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, JOB_ID, SALARY,
  RATIO_TO_REPORT(SALARY) OVER (PARTITION BY DEPARTMENT_ID, JOB_ID) as RATIO_SALARY
from employees
where JOB_ID in ('FI_ACCOUNT', 'IT_PROG')
;
